#!/usr/bin/env python
"""
Proxy Build Script
"""

import os
import sys
from glob import glob

# Add parent directory to path to find environment.py
sys.path.insert(0, '..')

# Import environment configuration from root
with open('../environment.py') as f:
    exec(f.read())

# Update paths for subproject
env.Append(CPPPATH=['../lib/include'])
env.Append(LIBPATH=['../lib'])

# Build the proxy application
env.Program('bin/proxy',
    source = glob('src/*.cpp'),
    LIBS = ['cryptolib', 'timelib', 'netlib', 'nucleus'])
